services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  accounts-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AccountsDb
    ports:
      - "5433:5432"
    volumes:
      - accounts-db-vol:/var/lib/postgresql/data/
    restart: unless-stopped
    
volumes:
  accounts-db-vol: